version: '2.4'
services:
  node:
    tty: true
    stdin_open: true
    container_name: is.valid.mongo
    build:
      context: .
      args:
        - NPM_TOKEN
    depends_on:
      - mongo
    volumes:
      - '.:/home/node/app:rw'
    user: 'node:node'

  mongo:
    image: mongo:3.4
